Chore: Automate version bumping and tagging
iotaledger/explorer pull request #1020
Opened 2024-01-26 13:54 UTC by msarcev

… bumping and tagging

# Description of change

- Added an npm script (and bash) to automate (and synchronise) version bumping and tagging

Closes https://github.com/iotaledger/explorer/issues/1009

## Type of change

- Enhancement (a non-breaking change which adds functionality)

2024-01-26 13:55 UTC, msarcev commented on tag_release.sh
> +# git push
Forgot to uncomment...
Please uncomment before merge!

2024-01-29 09:58 UTC, VmMad commented on tag_release.sh
> +read -n 1 -p "Do you want to push brench and tags ? (Enter): " CONFIRM_PUSH
```suggestion
read -n 1 -p "Do you want to push branch and tags ? (Enter): " CONFIRM_PUSH
```

2024-01-29 11:22 UTC, VmMad requested changes
Some suggestions

2024-01-29 11:22 UTC, VmMad commented on tag_release.sh
> +CURRENT_VERSION=$(sed -n 's/.*\version\": \"\([^"]*\).*$/\1/p' package.json)
This line is not working for me
![Screenshot from 2024-01-29 12-03-23](https://github.com/iotaledger/explorer/assets/88061365/e470fa8d-612a-4876-8ecd-2702a095d787)

2024-01-29 11:22 UTC, VmMad commented on tag_release.sh
> +git add .
Better not use `git add .` :sweat_smile: What about something like:
```sh
files_to_commit=("package.json" "package-lock.json")
folders_to_commit=("." "api" "client")

for folder in "${folders_to_commit[@]}"
do
    for file in "${files_to_commit[@]}"
    do
        git add "$folder/$file"
    done
done
```

2024-01-29 11:23 UTC, VmMad commented on tag_release.sh
> +CURRENT_VERSION=$(sed -n 's/.*\version\": \"\([^"]*\).*$/\1/p' package.json)
```suggestion
CURRENT_VERSION=$(sed -n 's/.*"version": "\([^"]*\)".*/\1/p' package.json)
```

2024-01-30 16:26 UTC, VmMad commented on scripts/tag_release.sh
> +git push --tags
Instead of this, i think it's better to just push the tag set previously, because anyone might push more tags than wanted

2024-01-30 16:44 UTC, VmMad approved these changes

2024-01-31 10:21 UTC, merged