feat: Add node selection & search
iotaledger/explorer pull request #1313
Opened 2024-03-20 09:10 UTC by panteleymonchuk

# Description of change

Highlight connection and search result on node click and change value in search bar.
Closes #1271

## Type of change

- feature

## How the change has been tested

1. Click to node. Expected result: connected nodes and lines are highlighted.
2. Change value in search bar. Expected result: nodes with matched id hightlighted.

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-03-21 14:31 UTC, begonaalvarezd requested changes
When I select a node, many get selected, I just clicked on 1
![image](https://github.com/iotaledger/explorer/assets/3624944/e6bf1244-9f73-47e9-9ce9-4d113c570eab)

2024-03-21 14:58 UTC, VmMad requested changes

2024-03-21 14:58 UTC, VmMad commented on client/src/features/visualizer-vivagraph/GraphContext.tsx
> +export const GraphProvider: React.FC<GraphProviderProps> = ({ children }) => {
```suggestion
export const GraphProvider: React.FC<React.PropsWithChildren> = ({ children }) => {
```

2024-03-21 14:58 UTC, VmMad commented on client/src/features/visualizer-vivagraph/GraphContext.tsx
> +    setIsVivaReady: Dispatch<boolean>;
```suggestion
    setIsVivaReady: Dispatch<boolean> | null;
```

2024-03-21 14:58 UTC, VmMad commented on client/src/features/visualizer-vivagraph/GraphContext.tsx
> +    setIsVivaReady: null as unknown as Dispatch<boolean>,
```suggestion
    setIsVivaReady: null,
```

2024-03-21 14:58 UTC, VmMad commented on client/src/features/visualizer-vivagraph/hooks/useFeed.ts
> +            graphContext.setIsVivaReady(true);
since the type is null | DIspatch 
```suggestion
            graphContext.setIsVivaReady?.(true);
```

2024-03-21 14:58 UTC, VmMad commented on client/src/features/visualizer-vivagraph/hooks/useFeed.ts
> +        }
question, what's this for?

2024-03-21 14:58 UTC, VmMad commented on client/src/features/visualizer-vivagraph/hooks/useFeed.ts
>              });
I think a hovering effect would be good too, to match the other visualizers

2024-03-21 14:58 UTC, VmMad commented on client/src/features/visualizer-vivagraph/hooks/useFeed.ts
> +                        }
Types need to be updated in `client/typings/vivagraph/index.d.ts` Line 19

2024-03-22 09:47 UTC, VmMad approved these changes
LGTM

2024-03-23 09:01 UTC, begonaalvarezd approved these changes
Code overall looks good, but after testing the node selection, when I click on a block, there seems to be random lines that are colores incorrectly in the tree, see example below, I'll merge to move forward with the development but i'll open an issue to investigate further
![image](https://github.com/iotaledger/explorer/assets/3624944/c3d78c0b-425d-4528-a6b0-c8b825bd08f9)

2024-03-23 09:02 UTC, begonaalvarezd commented on client/src/features/visualizer-vivagraph/definitions/constants.ts
> +export const EDGE_COLOR_CONFIRMING: number = 0xff5aaaff;
pushed

2024-03-23 09:05 UTC, merged