Chore: Polish Nova Output Page
iotaledger/explorer pull request #1318
Opened 2024-03-21 11:02 UTC by brancoder

# Description of change

closes #1305 

## Type of change

- Enhancement (a non-breaking change which adds functionality)

2024-03-23 10:43 UTC, begonaalvarezd requested changes
The CI is failing 🙏🏼 https://github.com/iotaledger/explorer/actions/runs/8400980359/job/23008866039?pr=1318#step:5:14

2024-03-23 11:02 UTC, begonaalvarezd requested changes
Added a mini comment, but everything works very nicely. With the mana units added to the total mana & the CI fixed, we can merge 🌷

2024-03-23 11:02 UTC, begonaalvarezd commented on client/src/helpers/nova/manaUtils.tsx
>          value: manaDetails?.totalMana,
We should also add units to the toplevel mana

2024-03-26 15:38 UTC, msarcev approved these changes

2024-03-26 16:44 UTC, begonaalvarezd requested changes
The total mana doesnt add up 🙏🏼 
![image](https://github.com/iotaledger/explorer/assets/3624944/0d822488-e80a-4f60-8495-8f6364332aba)
output `0xda6e52e4e01393beaf2ccc56a83ca85d63f45dd82274ed4ab17912b7b77a60f8ba8a00000000`

2024-03-26 17:12 UTC, msarcev commented
> The total mana doesnt add up 🙏🏼 ![image](https://private-user-images.githubusercontent.com/3624944/316960603-0d822488-e80a-4f60-8495-8f6364332aba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NzI5NjQsIm5iZiI6MTcxMTQ3MjY2NCwicGF0aCI6Ii8zNjI0OTQ0LzMxNjk2MDYwMy0wZDgyMjQ4OC1lODBhLTRmNjAtODQ5NS04ZjYzNjQzMzJhYmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjZUMTcwNDI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWJlNjJhZjdhYTM0NWE3MGQ0ZmE1YTI0NzY1MzRmZDFmNDE0NTk0ZmEwMzRiY2Q2OGUyYzM3Y2M0ZTdmOTMxYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nty9eraZTOF4gLZ8ug_mJ_Fn1GcXgrztx5aSzy1WWC8) output `0xda6e52e4e01393beaf2ccc56a83ca85d63f45dd82274ed4ab17912b7b77a60f8ba8a00000000`

Consequence of typescript being a joke. The types in the source are a "hopefully is this type" at best.

2024-03-27 10:03 UTC, begonaalvarezd approved these changes

2024-03-27 10:04 UTC, merged