feat: integrate play/pause feature
iotaledger/explorer pull request #1319
Opened 2024-03-21 15:17 UTC by VmMad

# Description of change

Fixes #1272 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-03-21 17:01 UTC, VmMad commented on client/src/features/visualizer-vivagraph/hooks/useFeed.ts
> +        renderer,
Nice, will update when that one gets merged so that there aren't conflicts!

2024-03-23 11:09 UTC, begonaalvarezd requested changes
The previous visualizer PR was merged, please update and fix conflicts 🙏🏼

2024-03-25 13:01 UTC, printmeow1 approved these changes

2024-03-26 16:48 UTC, begonaalvarezd approved these changes

2024-03-26 16:49 UTC, merged