feat: use official sdk package for nova and rename packages
iotaledger/explorer pull request #1360
Opened 2024-03-27 10:10 UTC by VmMad

# Description of change

Fixes #1326 
Fixes #868 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How the change has been tested

1. PR checks
2. Local build

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-03-27 13:38 UTC, begonaalvarezd requested changes
We should also cleanup `setup_nova.sh` right?

2024-03-27 13:38 UTC, begonaalvarezd commented on .github/workflows/nova-build-temp.yaml
>        deployment:
I guess we dont need this anymore

2024-03-27 13:38 UTC, begonaalvarezd commented on .github/workflows/nova-build-temp.yaml
> -    environment: release
this cant be removed

2024-03-27 14:12 UTC, VmMad commented
> We should also cleanup `setup_nova.sh` right?

@begonaalvarezd, @msarcev asked us to not drop the script yet, in case we need it

2024-04-22 09:58 UTC, begonaalvarezd requested changes

2024-04-22 09:58 UTC, begonaalvarezd commented on client/src/app/components/footer/Footer.scss
> +    ul li {
revert and ignore all css changes in this PR

2024-04-22 11:07 UTC, begonaalvarezd approved these changes

2024-04-22 11:09 UTC, merged