feat: review and update all info boxes
iotaledger/explorer pull request #1435
Opened 2024-04-23 17:10 UTC by panteleymonchuk

# Description of change

Closes #1349 

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-04-24 10:59 UTC, brancoder requested changes
We  should add some spacing between buttons when there are miltiple links:

![image](https://github.com/iotaledger/explorer/assets/52735957/8281b315-aaea-4ad4-b7e9-1e2a24fc7081)

2024-04-25 10:13 UTC, brancoder commented on client/src/assets/modals/nova/address/native-token.json
what i meant by this is that we can switch the links for Read more and Native tokens. wdyt?

2024-04-25 10:15 UTC, brancoder commented on client/src/assets/modals/nova/block/main-info.json
> +            "label": "Block Creation",
@begonaalvarezd wdyt?

2024-04-25 10:18 UTC, brancoder commented on client/src/assets/modals/nova/output/main-header.json
in the last commit looks like the search info got pasted in to the `output/main-header.json`.
for `output/main-header.json` we can use the info in my previous comment :arrow_up:

2024-04-25 10:21 UTC, brancoder commented on client/src/assets/modals/nova/search/main-header.json
> +    "description": "<p>All hex searches work with and without 0x prefix.<br />The following formats are supported:</p><ol><li><b>Blocks</b> 64 Hex characters</li><li><b>Block using Transaction Id</b>
Search criteria got pasted to output/main-header.json but it still has some issues in it like duplicated nft id

2024-04-25 11:52 UTC, brancoder approved these changes
nice work! LGTM :confetti_ball:

2024-04-25 12:53 UTC, begonaalvarezd requested changes

2024-04-25 12:53 UTC, begonaalvarezd commented on client/src/assets/modals/nova/block/main-info.json
> +    "title": "What is block",
Looking at the usage of this, im not sure why we even have block in the transaction metadat when the information is a bit mixed, we could actually remove this info
![image](https://github.com/iotaledger/explorer/assets/3624944/736a39df-e713-4bd9-836f-85bfaba0eeec)

2024-04-26 13:49 UTC, begonaalvarezd approved these changes

2024-04-26 13:51 UTC, merged