Add inspiration credit
iotaledger/explorer pull request #163
Opened 2022-02-13 12:36 UTC by viossat

The UI and some features of your v2 explorer is highly inspired from [thetangle.org](https://thetangle.org/) but it's never mentioned.
Feature requests also directly ask to copy thetangle.org (eg. #148, #75, #46, #81).
Similarly to [what the Hornet team did](https://github.com/gohornet/hornet/blob/b09279f3ffa3dc28432e7439c1a606c9ceabf8b5/plugins/spa/frontend/src/app/components/Explorer.tsx#L33) for their built-in explorer, this PR adds the mention of thetangle.org in the footer.

![just-blue-links-on-white-background](https://user-images.githubusercontent.com/3019820/153753247-b8ac4abd-af10-47ca-a410-0d1ae4204e92.png)

2022-02-23 16:24 UTC, laumair approved these changes

2022-03-04 11:34 UTC, laumair requested changes
Hi @viossat 👋 

Many thanks for the PR. We are happy to include this in the version 2 of the explorer. However, I have a couple of concerns:

1. I would suggest to alter the wording of the credits. A lot of effort was put into designing the layout of the explorer. It would be discrediting the effort of the design team if we use "heavily inspired" as it is not entirely accurate. Essentially both explorers are looking up the same dataset and it is quite common and natural that some areas (as you mentioned) are similar. Also, the feature requests you have mentioned are not yet included in this version. Saying `Some elements / parts of the explorer take inspiration from thetangle.org` would be more suitable in my honest opinion;
2. The current place of where we are displaying these credits don't look quite right. After having an internal discussion, it would be better to display them like below:

![Screenshot 2022-03-04 at 13 28 25](https://user-images.githubusercontent.com/20437468/156756200-5bee504d-e438-415d-9fec-e117de69415c.png)

2022-03-04 11:51 UTC, viossat commented
I prefer your way as well, feel free to push your changes.

2022-03-14 14:35 UTC, msarcev commented
Light
![image](https://user-images.githubusercontent.com/6864498/158194451-4cf010e3-b611-4948-ac09-662817067ed8.png)
Dark
![image](https://user-images.githubusercontent.com/6864498/158194494-20ba4aa2-a089-4340-9bf6-3ca45ea94b75.png)

2022-03-21 17:26 UTC, msarcev commented
![image](https://user-images.githubusercontent.com/6864498/159329566-aadcc62e-458d-4808-b16c-a2e8f6fa7fd4.png)

Looks like this now all the way down to 310px. Do we need to support smaller widths ?

2022-04-11 14:23 UTC, abbasabid approved these changes

2022-04-11 16:41 UTC, laumair approved these changes

2022-04-11 16:41 UTC, merged