Fix: Remove 'confirmations per second' indicator
iotaledger/explorer pull request #177
Opened 2022-02-16 12:07 UTC by brancoder

# Description of change

This PR aims to fix:
#146 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## Change checklist

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes

2022-02-23 10:41 UTC, laumair requested changes
https://github.com/iotaledger/explorer/issues/146#issuecomment-1048650631

2022-03-03 11:38 UTC, msarcev commented
LGTM.
Maybe change the title of the PR to a more descriptive one before merge ("Remove 'confirmations per second' indicator" ?).

2022-03-03 11:39 UTC, msarcev approved these changes

2022-04-11 14:19 UTC, abbasabid approved these changes

2022-04-11 14:44 UTC, laumair approved these changes

2022-04-11 14:44 UTC, merged