Feat: Added tooltip for special unlock conditions in associated outputs.
iotaledger/explorer pull request #484
Opened 2022-08-30 10:06 UTC by abbasabid

# Description of change

- Added a tooltip for Storage Deposit Return Unlock Condition - `arrow_back` icon will be shown for outputs which has SDRUC and on hover you can see the `Return Amount`.
- Added a tooltip for Expiration Unlock Condition - `hour_glass` icon will be shown for outputs which has EUC and on hover you can see the `Time left for expiration`.
- Added a tooltip for Timelock Unlock Condition - `clock` icon will be shown for outputs which has EUC and on hover you can see the `Time left for locked output`.

Aims to complete https://github.com/iotaledger/explorer/issues/447

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

In Associated Outputs Table on Address page for the outputs which has special unlock conditions like (SDRUC, EUC or TUC) you can see an icon beside copy icon and on hover on that icon you can see the data.

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes

2022-08-30 14:07 UTC, msarcev commented
<img width="392" alt="image" src="https://user-images.githubusercontent.com/6864498/187458451-05d2baeb-48df-4cc5-ab9b-703c580804a6.png">
I think it will look better if we have these icons "stay" in-line with the copy icon when expanded.
I think for this we will need to push the code inside `Output.tsx`. But maybe it's even better that way cause we will get this feature everywhere Output is used.
Also maybe try to color them yellow ? See how it looks.

2022-08-31 09:51 UTC, abbasabid commented
> <img alt="image" width="392" src="https://user-images.githubusercontent.com/6864498/187458451-05d2baeb-48df-4cc5-ab9b-703c580804a6.png">
> 
> I think it will look better if we have these icons "stay" in-line with the copy icon when expanded. I think for this we will need to push the code inside `Output.tsx`. But maybe it's even better that way cause we will get this feature everywhere Output is used. Also maybe try to color them yellow ? See how it looks.

Done.

2022-08-31 10:01 UTC, msarcev requested changes

2022-08-31 10:22 UTC, abbasabid commented on client/src/app/components/stardust/Output.tsx
> +            isSpecialCondition: false
Done.

2022-08-31 10:47 UTC, abbasabid commented on client/src/helpers/stardust/nameHelper.ts
> +                return "Basic";
Luca suggested that here https://github.com/iotaledger/explorer/issues/447#issuecomment-1231476297

2022-08-31 11:23 UTC, abbasabid commented on client/src/app/components/stardust/AssociatedOutput.tsx
> +            <td className="card overflow-unset">
Yes

2022-08-31 12:59 UTC, abbasabid commented on client/src/app/components/Tooltip.scss
> -    align-items: center;
The tooltip is using in three places and i checked that they look fine.

2022-08-31 13:20 UTC, abbasabid commented on client/src/app/components/stardust/Output.scss
> +    .icon {
Done.

2022-08-31 13:21 UTC, abbasabid commented on client/src/app/components/stardust/AssociatedOutput.tsx
> +import React, { useContext, useEffect, useState } from "react";
Resolved.

2022-09-01 08:52 UTC, msarcev commented
![image](https://user-images.githubusercontent.com/6864498/187873279-53baaa6a-0f73-4d57-b376-b805719578fc.png)
I think it looks good.

One thing we could improve here, is the formatting inside the tooltip. Make it so that the text is not broken in weird places.
Wdyt ?

2022-09-01 11:26 UTC, abbasabid commented
> ![image](https://user-images.githubusercontent.com/6864498/187873279-53baaa6a-0f73-4d57-b376-b805719578fc.png) I think it looks good.
> 
> One thing we could improve here, is the formatting inside the tooltip. Make it so that the text is not broken in weird places. Wdyt ?

Done.

2022-09-02 10:48 UTC, msarcev approved these changes

2022-09-02 10:49 UTC, merged