Fix: Spacing of inputs and outputs in transaction section
iotaledger/explorer pull request #583
Opened 2022-11-22 15:04 UTC by abbasabid

# Description of change

- Added left border for all the sections of inputs and outputs.
- Fix spacing between different sections.

Resolves https://github.com/iotaledger/explorer/issues/576

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

2022-11-23 10:32 UTC, brancoder requested changes
We can add the border and spacing changes to unlocks.
![image](https://user-images.githubusercontent.com/52735957/203524861-7504b682-4aef-4006-9d8e-66d80f0104e3.png)

2022-11-23 10:32 UTC, brancoder commented on client/src/app/components/stardust/TransactionPayload.scss
> +  .transaction.card--content .card--content__output {
Maybe we could change the `transaction` class name to  `transaction-payload_outputs` so its in line with BEM naming convention.

2022-11-23 14:15 UTC, brancoder commented on client/src/app/components/stardust/Unlocks.tsx
> +                style={{ height: "32px" }}
Can we try to avoid using hardcoded style values?

2022-11-24 11:20 UTC, brancoder requested changes
- Align the top and bottom margins so they have the same value

- Reduce the spacing between the rows as per #576  
> Spacing should be equal. Preferably the smaller of the two.

![outputs](https://user-images.githubusercontent.com/52735957/203771237-eb80e580-bf9b-4b83-9e7f-9d5a6068c1e8.png)

2022-12-02 15:47 UTC, msarcev commented
![image](https://user-images.githubusercontent.com/6864498/205331447-f2e77ebb-533c-4eea-aab1-64a41e466115.png)
Transaction payload now broken on mainnet...

2022-12-12 09:48 UTC, abbasabid commented
> ![image](https://user-images.githubusercontent.com/6864498/205331447-f2e77ebb-533c-4eea-aab1-64a41e466115.png) Transaction payload now broken on mainnet...

Fixed.

2022-12-12 16:38 UTC, brancoder approved these changes
LGTM

2022-12-13 07:37 UTC, merged