Feat: Add date picker to download transaction history.
iotaledger/explorer pull request #589
Opened 2022-11-24 14:36 UTC by abbasabid

# Description of change

- Add date picker to select period to download transaction history.

Resolves https://github.com/iotaledger/explorer/issues/579

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## Change checklist

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes

2022-12-02 15:53 UTC, msarcev commented
![image](https://user-images.githubusercontent.com/6864498/205332602-d8348ad9-0222-434a-8d05-1563063fa042.png)

Default state looks a bit weird.

2022-12-14 15:05 UTC, brancoder requested changes
Lint fix

2022-12-14 15:05 UTC, brancoder commented on client/src/services/stardust/stardustApiClient.ts
> +        targetDate: moment.Moment
Maybe we can use targetData as string so we don't have to import the moment lib just because of this one date.

2022-12-14 15:05 UTC, brancoder commented on api/src/services/stardust/chronicleService.ts
> +        targetDate: moment.Moment
Maybe we can accept targetDate as string instead of moment.Moment and than use the moment lib to get the date.

2022-12-15 13:55 UTC, brancoder approved these changes
LGTM

2022-12-15 13:57 UTC, merged