Feat: Added a component for truncated ids.
iotaledger/explorer pull request #636
Opened 2023-01-11 14:55 UTC by abbasabid

# Description of change

- Added a component for truncated ids on Landing page and Address Page.
- Ids can now be find with CTRL+F.

Resolves https://github.com/iotaledger/explorer/issues/587

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## Change checklist

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes

2023-01-13 18:35 UTC, msarcev commented
Please, `TruncateId` -> `TruncatedId` everywhere.

2023-01-19 09:10 UTC, brancoder requested changes
We should aim to have all truncated ids throughout the project displayed in the same form:
1. On Transaction page we still display them with 4 dots in the middle:
![image](https://user-images.githubusercontent.com/52735957/213400371-e8a82abe-683f-4ff7-9f86-c104b8823650.png)
2. On Address page all of the tabs for smaller screens display the ids with dots in the middle:
![image](https://user-images.githubusercontent.com/52735957/213401068-a42319c1-25d4-4c2f-ad3c-baedecea3c26.png)
![image](https://user-images.githubusercontent.com/52735957/213401205-d7d8f916-e899-48b7-be5c-70aa6d9152eb.png)

2023-01-19 09:10 UTC, brancoder commented on client/src/app/components/stardust/TruncatedId.scss
> +        width: 100px;
Maybe we should consider not limiting the `truncated-id` to `width: 100px;` rather we could have truncated-id be width:100% and add `max-width` on the container element or something along these lines. That way the truncated-id would shrink or get larger base on the containers width. Wdyt?

2023-01-20 09:11 UTC, brancoder reviewed
Maybe we should change the `.card` class on [this](https://github.com/iotaledger/explorer/blob/feat/findable-truncated-ids/client/src/app/components/stardust/AssociationSection.tsx#L150) line because this is a `td` in `association-section--table` and that doesn't seam correct. The `.card` class is used on the same page in section `.association-section--cards` where its appropriate. Wdyt?

2023-01-20 10:26 UTC, abbasabid commented
> this

Fixed.

2023-01-20 10:26 UTC, abbasabid commented
> Maybe we should change the `.card` class on [this](https://github.com/iotaledger/explorer/blob/feat/findable-truncated-ids/client/src/app/components/stardust/AssociationSection.tsx#L150) line because this is a `td` in `association-section--table` and that doesn't seam correct. The `.card` class is used on the same page in section `.association-section--cards` where its appropriate. Wdyt?

Fixed.

2023-01-20 11:10 UTC, brancoder approved these changes
LGTM

2023-01-20 11:15 UTC, merged