Seat: Split fetching of UTXOs of an address to separate endpoints
iotaledger/explorer pull request #648
Opened 2023-01-25 14:33 UTC by abbasabid

# Description of change

- Added separate endpoints for basic, alias and nft outputs by address and return outputResponse for respective outputIds.
- Use these new endpoints on AddressPage.

Resolves https://github.com/iotaledger/explorer/issues/645

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## Change checklist

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes

2023-01-26 08:58 UTC, msarcev requested changes

2023-01-26 08:58 UTC, msarcev commented on client/src/services/stardust/stardustTangleCacheService.ts
> +        if (!this._stardustSearchCache[networkId][`${address}-basic-outputs-details`]?.data?.outputs) {
Extract the "built key" to a `const`, please. For all three methods

2023-01-26 09:00 UTC, msarcev commented
Looks good mostly. Please, also remove the old route from the whole stack (the one that fetched outputs in bundle)

2023-01-27 12:34 UTC, brancoder requested changes

2023-01-27 13:00 UTC, abbasabid commented on client/src/services/stardust/stardustTangleCacheService.ts
> +                this._stardustSearchCache[networkId][`${address}-basic-outputs-details`] = {
Done.

2023-01-27 13:52 UTC, brancoder approved these changes
LGTM

2023-01-27 18:28 UTC, msarcev commented on client/src/app/routes/stardust/AddressPage.tsx
> +            void loadNftAddressData();
Naming for these methods above sounds a bit misleading, just call it what it is... `loadAddressBasicOutputs`, `loadAddressAliasOutputs`

2023-01-31 11:32 UTC, msarcev approved these changes

2023-01-31 11:33 UTC, merged