chore: Add prettier configs
iotaledger/explorer pull request #939
Opened 2023-12-28 09:36 UTC by msarcev

# Description of change

- [x] Added prettier configs for client/api
- [ ] Format whole codebase

## Type of change

- Enhancement (a non-breaking change which adds functionality)

2024-01-08 10:29 UTC, begonaalvarezd requested changes
Lets do:
- Add root package scripts so that prettier can be tested && tested&fixed (staged files only, we have it in fiefly) https://github.com/lint-staged/lint-staged
- Format the whole code
- Add format check to the CI (prettier/linter, we have it in firefly too)

2024-01-11 14:34 UTC, msarcev commented
Please consider:
* Reverting the formatting on config files that are outside of respective `src` folder (probably out matcher needs to be something like `ts,js,tsx,scss`)
* Check the prettier configs in my initial commit, if they are good let's use those :D

2024-01-15 15:01 UTC, begonaalvarezd reviewed
🔥

2024-01-15 15:01 UTC, begonaalvarezd approved these changes

2024-01-15 15:02 UTC, merged